### ISSUE TITLE
Serial Port Custom baud rate

### ISSUE THREAD

**Issue by i3130002** [microsoft/vscode-arduino#1175]
I've been using Arduino extension for VSCode for a while and I still can't use it's serial port using custom baud rate (Or even something that it has been configured in board manager :D 
Please consider **adding more baud rates** and also giving us the option to **use a custom one**(Currently it do not accept any custom one).
![image](https://user-images.githubusercontent.com/11602376/103999656-69716600-51b2-11eb-95b1-2c5ad4f3c364.png)
![image](https://user-images.githubusercontent.com/11602376/104000004-e270bd80-51b2-11eb-9ae6-6c256ce2917e.png)

**Comment by kickshawprogrammer** [comment]
You can change it, at least on windows, but it's a manual process right now.

Open the file .vscode\extensions\vsciot-vscode.vscode-arduino-0.3.4\out\src\serialmonitor\serialMonitor.js in the user's directory.

Go to the bottom of the file and there you will see a SerialMonitor.DEFAULT_BAUD_RATE = 
Set it to the desired value and save.

Restart VSC.

Default speed changed.

I set my default to 74880 since ESP's default to that value...

It would be nice, however, to have this as a JSON setting in the global / project settings to be sure though...

Regards,

**Comment by i3130002** [comment]
> You can change it, at least on windows, but it's a manual process right now.

Thanks @kickshawprogrammer  Will check it out.

**Comment by gcampbell-msft** [comment]
@i3130002 We have recently updated the Arduino extension to depend on a new standalone Serial Monitor extension, please upgrade your arduino extension and try out this new feature!

Let us know if it solves your issue or if the issue still persists!

**Comment by i3130002** [comment]
> tly updated the Arduino extension to depend on a new standalone Serial Monitor extension, please upgrade your arduino extension and try out this new feature!

Glad to hear that, Although I'm not in the industry anymore. 

Hopefully, others can verify this. Thanks for your hard work.
