### ISSUE TITLE
Can't change serial port line ending sequence

### ISSUE THREAD

**Issue by roninbar** [microsoft/vscode-arduino#1324]
In #972 it says:

> Thanks for your contributions. Line endings selection has been removed and replaced by default ending with the carriage return and the line feed `\r\n`.

_Originally posted by @hellyzh in https://github.com/microsoft/vscode-arduino/issues/972#issuecomment-604878823_

but it doesn't say how to change this setting to any other value, e.g. `none`. I went over all the settings and all the commands and couldn't find a way to do it.

**Comment by JaredTheWolf** [comment]
This needs some attention. Without being able to change line endings, source code needs to be changed to account for newlines, just because this plugin no longer supports changing the line ending. There seems to be no reasoning as to why this was changed, and makes the serial monitor effectively useless in my case.

**Comment by gcampbell-msft** [comment]
@roninbar We have recently updated the Arduino extension to depend on a new standalone Serial Monitor extension, please upgrade your arduino extension and try out this new feature!

Let us know if it solves your issue or if the issue still persists!

**Comment by roninbar** [comment]
@gcampbell-msft Yes, it works! Thanks!
