### ISSUE TITLE
Arduino path - Linux Manjaro KDE 5.23

### ISSUE THREAD

**Issue by mgirdwood** [microsoft/vscode-arduino#1394]
Hi
I followed the previous post on this however i seem to be unable to duplicate the answer.  VS code installed via Flatpack (  simply as with the AUR version it could not see the Arduino extension from Miscrosoft.)  Arduino 1.8 IDE installed and working as a separate application.  
When trying to "select programmer " in VS Code the path error pops up. 
using terminal to try locate the path i have :
pacman -Ql arduino                                                                   ✔ 
arduino /usr/
arduino /usr/bin/
arduino /usr/bin/arduino
arduino /usr/share/
arduino /usr/share/applications/
arduino /usr/share/applications/arduino.desktop
arduino /usr/share/arduino/

I have tried all the above in the VS Arduino extension settings but non seem to be correct.   restart of VScode after each change.  Any pointers would be very welcome
Thanks

**Comment by benmcmorran** [comment]
I'm wondering if flatpak is sandboxing your VS Code instance and preventing it from launching the Arduino IDE. Can you try these steps?

1. Run `which arduino` from a terminal outside of VS Code to get the path to the Arduino IDE.
2. From the integrated terminal in VS Code, try to run the Arduino IDE from the path you got in step 1. If it fails to launch, then the issue lies with your flatpak configuration, not this extension.
