### ISSUE TITLE
Unable to use extension when installing Arduino from Windows Store

### ISSUE THREAD

**Issue by akaroml** [microsoft/vscode-arduino#145]
Feedback from internal partner.

**Comment by liydu** [comment]
Wait to see what **arduino-cli** can provide.

**Comment by czgtest** [comment]
@liya Can you help to review again?

**Comment by liydu** [comment]
If we switch to new build system like `arduino-cli`, there is no longer dependency for Arduino IDE.
A short-term mitigation is to add FAQ.

**Comment by mvadu** [comment]
Any progress on this one? Microsoft (i.e. parent company of this repo) pushes for developers to package Win32 applications like Arduino IDE to be store apps. But if there is not a way to invoke then its a dead end. `arduino-cli` supports this use case, but this repo is just pushing the milestones since Mar!!

**Comment by Xepol** [comment]
I vote for supporting arduino-cli, that would get rid of that dang splash screen too.

**Comment by JerryYangKai** [comment]
In our get started tutorials, it said install arduino IDE instead of windows store's app.
