### ISSUE TITLE
Can't open Arduino path

### ISSUE THREAD

**Issue by agnessap** [microsoft/vscode-arduino#1466]
Hi, I'm trying to program an Arduino in VScode and I´ve specified the Arduino path in the JSON settings and I have installed the Arduino IDE, but VScode can still not find the path. 
I´ve checked multiple times, and the path seems to be correct.
Does anyone know how I can fix this issue? :)
<img width="599" alt="Screenshot 2022-03-06 at 23 34 06" src="https://user-images.githubusercontent.com/86083439/156945099-ae708220-d380-4681-a374-3d141efc0bf3.png">

**Comment by BelKed** [comment]
It seems like you've set path of [`arduino-cli`](https://github.com/arduino/arduino-cli), not [Arduino IDE](https://github.com/arduino/Arduino).

In my case, binary of [`arduino-cli`](https://github.com/arduino/arduino-cli) is called `arduino-cli`, not just `arduino`, so that could be the problem. In that case, you should change `arduino.commandPath`.

But if you want to use [Arduino IDE](https://github.com/arduino/Arduino), you should change your `arduino.path`, because its version is probably not `0.21.1`...

You can find more info in [README.md](https://github.com/microsoft/vscode-arduino#options).

**Comment by DeadlySurgeon** [comment]
> It seems like you've set path of [`arduino-cli`](https://github.com/arduino/arduino-cli), not [Arduino IDE](https://github.com/arduino/Arduino).
> 
> In my case, binary of [`arduino-cli`](https://github.com/arduino/arduino-cli) is called `arduino-cli`, not just `arduino`, so that could be the problem. In that case, you should change `arduino.commandPath`.
> 
> But if you want to use [Arduino IDE](https://github.com/arduino/Arduino), you should change your `arduino.path`, because its version is probably not `0.21.1`...
> 
> You can find more info in [README.md](https://github.com/microsoft/vscode-arduino#options).

The documentation, as well as the errors I'm getting, tell me that the CLI needs to be specified under `arduino.path`.

![image](https://user-images.githubusercontent.com/60354262/163731414-b15c705b-7bc1-47c6-97ae-8b386bf5b5d2.png)

But the funny thing is, this doesn't even work for me.

**Comment by benmcmorran** [comment]
Hi @DeadlySurgeon. It looks like there is special case handling for finding the Arduino executable on Mac.

https://github.com/microsoft/vscode-arduino/blob/22eec0921e67d9922e505248293047ce83509d35/src/arduino/arduinoSettings.ts#L138-L143

https://github.com/microsoft/vscode-arduino/blob/22eec0921e67d9922e505248293047ce83509d35/src/common/util.ts#L442-L448

Based on this logic, you should be able to specify to specify the full path to `Arduino*.app` as `arduino.path`. Does that work for you?

**Comment by DeadlySurgeon** [comment]
@benmcmorran 
>  It looks like there is special case handling for finding the Arduino executable on Mac.

This is on Linux.
