### ISSUE TITLE
how to config compiler warning level

### ISSUE THREAD

**Issue by resos1** [microsoft/vscode-arduino#1508]
Hello,
I'm looking for the setting to change the compiler warning level, equivalent config in preferences window of arduino ide (attached image)
![1](https://user-images.githubusercontent.com/49358817/171831535-29bde694-1ff9-4248-9ee0-af217d09f8db.jpg)

I've already tried  #1392  but it doesn't worked for me, that kept adding -w parameter and ignoring the -Wall parameter.
I Prefer to set this setting to "Default", does it means that I just need to remove -w parameter, right? how can I do that?

**Comment by benmcmorran** [comment]
Hi @resos1! #1392 is almost right, but you just need to set a different preference. Try adding this to your `arduino.json`. You can see all the preferences by viewing `%LOCALAPPDATA%\Arduino15\preferences.txt`.

```json
    "buildPreferences": [["compiler.warning_level", "default"]]
```

**Comment by Benik3** [comment]
Does this should still works?
I tried it and still got the same output. Maybe it doesn't work with the new CLI?
I tried to add into arduino.json:
```
"buildPreferences": [
        ["build.extra_flags", "-Wall"],
        ["compiler.cpp.extra_flags", "-Wall"],
        ["compiler.warning_level", "all"]
    ]
```

**Comment by da-phil** [comment]
@Benik3 
> Does this should still works?

At least not for me, and it's clear why not, you already explained it:
The `buildPreferences` list is getting translated to `--build-property STRING`  arduino CLI arguments, and the actual config to change the warnings level is a separate CLI option `--warnings STRING`.

It would be really cool if vscode-arduino would expose the same config option in the main config, otherwise it's impossible to append this CLI option to the internal arduino CLI invocations.
