### ISSUE TITLE
No endline option for Serial Console input

### ISSUE THREAD

**Issue by simon-bonin** [microsoft/vscode-arduino#1589]
Issue description: 

While entering a value using the serial console, there is no endline option and the default (new line) option is parsed defaulting to a 0 value.

Therefore, if the program waits for a second input, it takes the newline (from the previous input) as the second intput and refuses to parse the non-integer value and thus parses 0. 

The option already exists in the first version of arduino IDE, so I have to revert back to using it while testing console inputs. 

Expected behavior: 
![image](https://user-images.githubusercontent.com/124949012/217986373-1f66d572-f72d-4820-9778-ab68ace94453.png)

Issue (only a single input was entered): 
![image](https://user-images.githubusercontent.com/124949012/217989315-074ed836-1096-4ebc-ac5b-a2e4356149c2.png)

**Comment by benmcmorran** [comment]
@simon-bonin We're planning to switch the Arduino extension over to using the [Serial Monitor extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-serial-monitor&ssr=false#overview) soon instead of the current built-in serial monitor. The Serial Monitor extension supports setting the line ending, along with many other options and usability improvements that aren't available in the Arduino extension. You can try it out early by installing it from the VS Code Marketplace.

**Comment by simon-bonin** [comment]
Hi @benmcmorran,

I didn't know it was available, I will try it out asap! Thanks for the input and for your quick reply. 

Have a great day!
