### ISSUE TITLE
[Lib manager] Add 'Install and Include Library' button

### ISSUE THREAD

**Issue by formulahendry** [Microsoft/vscode-arduino#221]
With 'Install and Include Library' button, I no longer need to 'Install' first, then wait for the download is done, then click 'Include Library'.

![image](https://cloud.githubusercontent.com/assets/1050213/24787084/c0af6632-1b98-11e7-8fec-c3ab6a51005c.png)

**Comment by czgtest** [comment]
I don't think @formulahendry request is reasonable. because not everyone needs to do include Library after install.   and there is no need to add this extra button to UI.
Install button : install Library action
Include Library button : include reference in code.
![image](https://user-images.githubusercontent.com/35018765/37075648-c6da3f92-220d-11e8-990b-eaad414c2eaf.png)

**Comment by czgtest** [comment]
@ArthurMa1978  Can you help to confirm for it?

**Comment by czgtest** [comment]
In Library manager page, Install and Include Library button already meet this request, so close it
