### ISSUE TITLE
Unable to start debugging. No process is associated with this object.

### ISSUE THREAD

**Issue by yuwzho** [microsoft/vscode-arduino#325]
When I click the run button in VSCode, I get such error message: `Unable to start debugging. No process is associated with this object.` Need I update some other configs?

**Comment by stuartaw** [comment]
So, these two issues get closed with zero feedback, referring to each other, as if the answer would be in the other issue? nice style andxu! you should close one of the two and reply in the other.
Perhaps I could suggest just a small hint as to why this happens?

**Comment by zfields** [comment]
I had this same issue, and it turns out OpenOCD was crashing for me. The output from stdout wasn't forwarded to the same place I got the `Unable to start debugging. No process is associated with this object.` message.

I only got the crash message when I ran it from a terminal inside of VSCode. Once I corrected the crash, then everything started working.

**Comment by RidhimaDebanth** [comment]
how to correct the crash ..please help
