### ISSUE TITLE
"Arduino Examples" showed twice

### ISSUE THREAD

**Issue by reyang** [Microsoft/vscode-arduino#496]
Plug in the DevKit, unplug it, then plug in again, there will be two "Arduino Examples" tabs opened.
Expect only one.

![image](https://user-images.githubusercontent.com/17327289/37311751-ce9b9ae0-2605-11e8-972c-c0bfa1f14bc4.png)

**Comment by czgtest** [comment]
@reyang  which OS are you using ?

I try on my win10 , but not repro this issue
Arduino extension version: 0.2.11
vscode : 1.21.0

**Comment by reyang** [comment]
Microsoft Windows [Version 10.0.16299.248]

![image](https://user-images.githubusercontent.com/17327289/37358789-2bebe972-26a9-11e8-9df3-c34140e229e1.png)

Arduino for Visual Studio Code v0.2.11
Azure Account v0.3.1

**Comment by czgtest** [comment]
I can repro this issue too.

@Sneezry  Can you help to fix this issue ?

![image](https://user-images.githubusercontent.com/35018765/37443455-38ccedc2-2847-11e8-98ef-72ad17f4173e.png)

**Comment by Sneezry** [comment]
This issue happens when no document open in vscode. Arduino Examples page is open in the second column (https://github.com/Microsoft/vscode-arduino/blob/0bb2b7392e67b2f59a67382a210fbbd2095a1206/src/extension.ts#L113). When on document open, vscode will open it in the first column, and when we re-plugin DevKit, vscode open a new one in the second column.

**Comment by Sneezry** [comment]
I have post an issue here: https://github.com/Microsoft/vscode/issues/46161

**Comment by ArthurMa1978** [comment]
Since this is not a issue from our extension, and VS Code planned to  fix it.
Close it on our side.
