### ISSUE TITLE
autodefine paths for intellisence

### ISSUE THREAD

**Issue by r3d9u11** [Microsoft/vscode-arduino#547]
Hi. Is it possible automatically detect and fill "generic" paths like a:
```
"<...PATH_TO_ARDUINO...>/hardware/tools/avr/avr/include",
"<...PATH_TO_ARDUINO...>/hardware/tools/avr/lib/gcc/avr/4.9.2/include",
"<...PATH_TO_ARDUINO...>/hardware/arduino/avr/cores/arduino",
"<...PATH_TO_ARDUINO...>/hardware/arduino/avr/variants/mega",
```
in c_cpp_properties.json after type of board was selected (and arduino.json was configured before)? It would be cool. Thanks!

**Comment by Sneezry** [comment]
This is a very very old issue, but it is still not solved completely: https://github.com/Microsoft/vscode-arduino/issues/438

In short, `includePath` is not recursive currently, and it depends on C/CPP extension (which is out of our control).

I had commited a workaround to fix it temporary: https://github.com/Microsoft/vscode-arduino/pull/538

This issue is very annoying, and we will keep to seek final solution.

**Comment by r3d9u11** [comment]
@Sneezry thank you for your answer and useful links! (sorry for duplicate, I can close this issue. or leave it opened for other users who interested in this theme)

**Comment by Sneezry** [comment]
Then I will close this issue. Please post any update in #438 to follow this issue.
