### ISSUE TITLE
Show more detail info during upload

### ISSUE THREAD

**Issue by ArthurMa1978** [Microsoft/vscode-arduino#632]
the upload and verify show the same message 
![image](https://user-images.githubusercontent.com/20514459/43818277-78fbded0-9b10-11e8-9c71-b753da5f56b8.png)

consider to have the accurate message of corresponding actions, like:
Upload - verifying
Upload - uploading to the device

Compile - verifying

**Comment by czgtest** [comment]
1.The output of the upload and verify is already different. 
when run verify/upload command ,you can see the hightlight message
![image](https://user-images.githubusercontent.com/35018765/44141885-09b8c6ae-a0b1-11e8-8f09-2609785e3406.png)
![image](https://user-images.githubusercontent.com/35018765/44142366-8baf13f6-a0b2-11e8-95a3-2e5ea6e351fb.png)
![image](https://user-images.githubusercontent.com/35018765/44142503-e96c729a-a0b2-11e8-9ff9-8dfccc15eeab.png)

2.when upload sketch, it will run 3 steps :verify, complie ,upload
verify step will do ,  it is expect.
                   Loading configuration...
                   Initializing packages...
                   Preparing boards...
                   Verifying...

all output of these steps are raw output of arduino, it is by design.
