### ISSUE TITLE
Re: [Microsoft/vscode-arduino] i verify and revived this error :Exit with code=undefined (#577)

### ISSUE THREAD

**Issue by vsanagustin** [Microsoft/vscode-arduino#647]
Hjk

**Comment by czgtest** [comment]
@vsanagustin  this error will repro when arduino.commandPath and arduino.path is wrong in old version of Arduino extension,   but in latest version  this issue is fix,   
if you still revived this error,  maybe it caused by other reason,   Can you share more detail about how to repro on it  ?   Thanks a lot!

**Comment by czgtest** [comment]
@vsanagustin  Can you share your settings.json ?

**Comment by dublehw** [comment]
Hi,
seems i get this as only message when verifing or uploading. Dispite that the built seems to work as i get a binary.

Output:

[Starting] Verify sketch - arduino\some.ino
[Error] Exit with code=undefined

or

[Starting] Upload sketch - arduino\some.ino
[Error] Exit with code=undefined

i have no arduino command path nor changed i the default path so no changes in the settings.json.

Im using Arduino IDE 1.8.7 and 0.2.20 of the extension.

Br

**Comment by wize1** [comment]
Hi, I also have same problem.

any fix on this? 

btw im new to vscode where do i find "settings.json" to share?

**Comment by czgtest** [comment]
Arduino 1.8.7 has some breaking changes,  please use Arduino 1.8.6.

**Comment by wize1** [comment]
Thanks for the answer ... but im using just normal visual studio now
