### ISSUE TITLE
[User Feedback] Remember last used baud rate for serial monitor

### ISSUE THREAD

**Issue by Sneezry** [microsoft/vscode-arduino#709]

**Comment by YakovL** [comment]
how can I check the actual value of baud rate? A friend of mine showed me that in board config I should see something like

![image](https://user-images.githubusercontent.com/1131924/100542774-3952b100-325d-11eb-9424-452ae3ab292e.png)

but what I actually see is

![image](https://user-images.githubusercontent.com/1131924/100542782-4cfe1780-325d-11eb-85ad-df3146a61ff1.png)

Since I'm having *major* problems with upload speed (8 minutes for a simple sketch) and I tried to set baud rate to 115200 via ctrl + shift + p → Change Baud Rate, but the problem stays, I'd like to check if baud rate is actually set or not. Having baud rate persistent would be nice, too.

Should I open a new issue? I failed to find anything similar.

**Comment by adiazulay** [comment]
@YakovL can you open a new issue, I think this problem is stemming from somewhere else and not the baud rate. Do you experience the same upload speeds in the the Arduino IDE?

**Comment by gcampbell-msft** [comment]
Hi @Sneezry, we have recently updated the Arduino extension to depend on a new [Serial Monitor extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-serial-monitor). Please update to the newest version of the Arduino extension and let us know what you think and if this issue is still relevant!
